# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f14685ae446f789d935917792a1427b5df000b28ea982e6beba496be7123e25faeaba3df08c6d987ffc23424967ebb557e4ed4d0241e6278c2c9c2ec97085c4d

test:
  secret_key_base: 80821fbd7afcd076998d44de37166dc681d608e60d3ec81c804d8c137fa65fd726b6f7ab04c64effad95c1db98f8cb59fe43cf68ba36c16b7dd2d2825ca22c25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
